### ISSUE TITLE
[BUG] - Description text is repeated

### ISSUE THREAD

**Issue by TrofimSelbs** [esheyw/find-the-culprit#7]
Hey, thank you for continuing to maintain this wonderful module! Here is a visual bug that I have found:
![SCR-20240726-llew](https://github.com/user-attachments/assets/5a1a9dcd-eae3-405e-95d9-8aaff0e05f48)

**Comment by esheyw** [comment]
Hi, sorry for missing this, I haven't been getting notifications properly for this repo. 

This was because I forgot to change something after copy & paste, stupid mistake. Fortunately version 3.0 involved a complete overhaul of the instructional text and how it's displayed, so this was incidentally fixed.

**Comment by TrofimSelbs** [comment]
Nah, everything is good. This is just a silly bug. Thank you for supporting this essential tool, you are awesome!
