### ISSUE TITLE
Clicking a checkbox while filtering by name refreshes the filter but does not check the box

### ISSUE THREAD

**Issue by GambetTV** [esheyw/find-the-culprit#9]
When you use Find the Culprit's filter, and then click one of the checkboxes, you'll see a brief flash of the filter refreshing, and the checkbox won't be checked. After this you can click on the checkbox again and it works, but this is an annoying little hiccup of a bug.

**Comment by esheyw** [comment]
Hi, sorry for missing this, I haven't been getting notifications properly for this repo. 

The flicker is because the render wasn't building in the hidden class, it was having to be applied immediately post render. In addition to all the other things version 3.0 changed, I now grab the hidden state pre-render and carry it over, eliminating the flicker, theoretically. If you're still getting some in v3 let me know, but closing this for now.
